[2025-02-02T18:01:04.565+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T18:01:04.584+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_etl.extract_orders scheduled__2024-07-11T08:00:00+00:00 [queued]>
[2025-02-02T18:01:04.594+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_etl.extract_orders scheduled__2024-07-11T08:00:00+00:00 [queued]>
[2025-02-02T18:01:04.595+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-02T18:01:04.613+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_orders> on 2024-07-11 08:00:00+00:00
[2025-02-02T18:01:04.622+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1081) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-02T18:01:04.624+0000] {standard_task_runner.py:72} INFO - Started process 1100 to run task
[2025-02-02T18:01:04.622+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'northwind_etl', 'extract_orders', 'scheduled__2024-07-11T08:00:00+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/northwind_etl/northwind_etl.py', '--cfg-path', '/tmp/tmpe8anhwns']
[2025-02-02T18:01:04.625+0000] {standard_task_runner.py:105} INFO - Job 202: Subtask extract_orders
[2025-02-02T18:01:04.681+0000] {task_command.py:467} INFO - Running <TaskInstance: northwind_etl.extract_orders scheduled__2024-07-11T08:00:00+00:00 [running]> on host dab7efa052da
[2025-02-02T18:01:04.765+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriel' AIRFLOW_CTX_DAG_ID='northwind_etl' AIRFLOW_CTX_TASK_ID='extract_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T08:00:00+00:00'
[2025-02-02T18:01:04.769+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T18:01:04.787+0000] {logging_mixin.py:190} INFO - table: orders, date: {{ds}}
[2025-02-02T18:01:04.787+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/northwind_etl/northwind_etl.py", line 30, in _lab_extrat_table_to_parquet
    engine = create_engine(POSTGRES_CONN)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 516, in create_engine
    u, plugins, kwargs = u._instantiate_plugins(kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_instantiate_plugins'
[2025-02-02T18:01:04.805+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=northwind_etl, task_id=extract_orders, run_id=scheduled__2024-07-11T08:00:00+00:00, execution_date=20240711T080000, start_date=20250202T180104, end_date=20250202T180104
[2025-02-02T18:01:04.900+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T18:01:04.901+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 202 for task extract_orders ('NoneType' object has no attribute '_instantiate_plugins'; 1100)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/northwind_etl/northwind_etl.py", line 30, in _lab_extrat_table_to_parquet
    engine = create_engine(POSTGRES_CONN)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 516, in create_engine
    u, plugins, kwargs = u._instantiate_plugins(kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_instantiate_plugins'
[2025-02-02T18:01:04.922+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-02T18:01:04.938+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-02T18:01:04.940+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-05T02:26:25.257+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T02:26:25.276+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_etl.extract_orders scheduled__2024-07-11T08:00:00+00:00 [queued]>
[2025-02-05T02:26:25.289+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_etl.extract_orders scheduled__2024-07-11T08:00:00+00:00 [queued]>
[2025-02-05T02:26:25.290+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-05T02:26:25.393+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_orders> on 2024-07-11 08:00:00+00:00
[2025-02-05T02:26:25.404+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=15521) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-05T02:26:25.405+0000] {standard_task_runner.py:72} INFO - Started process 15537 to run task
[2025-02-05T02:26:25.404+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'northwind_etl', 'extract_orders', 'scheduled__2024-07-11T08:00:00+00:00', '--job-id', '460', '--raw', '--subdir', 'DAGS_FOLDER/northwind_etl/northwind_etl.py', '--cfg-path', '/tmp/tmp4myb2t9l']
[2025-02-05T02:26:25.406+0000] {standard_task_runner.py:105} INFO - Job 460: Subtask extract_orders
[2025-02-05T02:26:25.473+0000] {task_command.py:467} INFO - Running <TaskInstance: northwind_etl.extract_orders scheduled__2024-07-11T08:00:00+00:00 [running]> on host 09d05643d017
[2025-02-05T02:26:25.615+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriel' AIRFLOW_CTX_DAG_ID='northwind_etl' AIRFLOW_CTX_TASK_ID='extract_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T08:00:00+00:00'
[2025-02-05T02:26:25.616+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T02:26:25.636+0000] {logging_mixin.py:190} INFO - table: orders, date: 2024-07-11
[2025-02-05T02:26:25.692+0000] {logging_mixin.py:190} INFO - Total records extracted: 830
[2025-02-05T02:26:25.692+0000] {logging_mixin.py:190} INFO - Columns present: order_id, customer_id, employee_id, order_date, required_date, shipped_date, ship_via, freight, ship_name, ship_address, ship_city, ship_region, ship_postal_code, ship_country
[2025-02-05T02:26:25.747+0000] {logging_mixin.py:190} INFO - Extraction saved successfully at: /opt/***/data/postgres/orders/2024-07-11/orders.parquet
[2025-02-05T02:26:25.748+0000] {python.py:240} INFO - Done. Returned value was: Extracted 830 records from orders
[2025-02-05T02:26:25.781+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T02:26:25.782+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=northwind_etl, task_id=extract_orders, run_id=scheduled__2024-07-11T08:00:00+00:00, execution_date=20240711T080000, start_date=20250205T022625, end_date=20250205T022625
[2025-02-05T02:26:25.863+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-05T02:26:25.895+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-05T02:26:25.910+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
