[2025-02-05T01:12:22.968+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T01:12:22.985+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_loader.load_postgres manual__2025-02-05T01:12:22.296373+00:00 [queued]>
[2025-02-05T01:12:22.993+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_loader.load_postgres manual__2025-02-05T01:12:22.296373+00:00 [queued]>
[2025-02-05T01:12:22.994+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-05T01:12:23.006+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): load_postgres> on 2025-02-05 01:12:22.296373+00:00
[2025-02-05T01:12:23.012+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10311) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-05T01:12:23.013+0000] {standard_task_runner.py:72} INFO - Started process 10312 to run task
[2025-02-05T01:12:23.012+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'northwind_loader', 'load_postgres', 'manual__2025-02-05T01:12:22.296373+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/northwind_etl/northwind_loader_mel.py', '--cfg-path', '/tmp/tmp4040w8m9']
[2025-02-05T01:12:23.013+0000] {standard_task_runner.py:105} INFO - Job 58: Subtask load_postgres
[2025-02-05T01:12:23.048+0000] {task_command.py:467} INFO - Running <TaskInstance: northwind_loader.load_postgres manual__2025-02-05T01:12:22.296373+00:00 [running]> on host 09d05643d017
[2025-02-05T01:12:23.115+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriel' AIRFLOW_CTX_DAG_ID='northwind_loader' AIRFLOW_CTX_TASK_ID='load_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T01:12:22.296373+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T01:12:22.296373+00:00'
[2025-02-05T01:12:23.116+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T01:12:23.153+0000] {docker.py:379} INFO - Starting docker container from image meu-meltano
[2025-02-05T01:12:23.556+0000] {docker.py:73} INFO - Iniciando processo...
[2025-02-05T01:12:23.556+0000] {docker.py:73} INFO - 1. Verificando diret√≥rio atual
[2025-02-05T01:12:23.557+0000] {docker.py:73} INFO - /meltano/demo-project
[2025-02-05T01:12:23.557+0000] {docker.py:73} INFO - 2. Testando comando date
[2025-02-05T01:12:23.558+0000] {docker.py:73} INFO - Wed Feb  5 01:12:23 UTC 2025
[2025-02-05T01:12:23.559+0000] {docker.py:73} INFO - 3. Listando ambiente
[2025-02-05T01:12:23.559+0000] {docker.py:73} INFO - PYTHON_SHA256=bfb249609990220491a1b92850a07135ed0831e41738cf681d63cf01b2a8fbd1
[2025-02-05T01:12:23.559+0000] {docker.py:73} INFO - HOSTNAME=5cdbc8508cf8
[2025-02-05T01:12:23.560+0000] {docker.py:73} INFO - PYTHON_VERSION=3.10.16
[2025-02-05T01:12:23.560+0000] {docker.py:73} INFO - PWD=/meltano/demo-project
[2025-02-05T01:12:23.560+0000] {docker.py:73} INFO - HOME=/root
[2025-02-05T01:12:23.561+0000] {docker.py:73} INFO - LANG=C.UTF-8
[2025-02-05T01:12:23.561+0000] {docker.py:73} INFO - GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D
[2025-02-05T01:12:23.561+0000] {docker.py:73} INFO - SHLVL=1
[2025-02-05T01:12:23.562+0000] {docker.py:73} INFO - MELTANO_PROJECT_ROOT=/meltano/demo-project
[2025-02-05T01:12:23.562+0000] {docker.py:73} INFO - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[2025-02-05T01:12:23.562+0000] {docker.py:73} INFO - _=/usr/bin/env
[2025-02-05T01:12:23.563+0000] {docker.py:73} INFO - 4. Verificando meltano
[2025-02-05T01:12:23.563+0000] {docker.py:73} INFO - /usr/local/bin/meltano
[2025-02-05T01:12:24.776+0000] {docker.py:73} INFO - meltano, version 3.6.0
[2025-02-05T01:12:25.205+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T01:12:25.205+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=northwind_loader, task_id=load_postgres, run_id=manual__2025-02-05T01:12:22.296373+00:00, execution_date=20250205T011222, start_date=20250205T011222, end_date=20250205T011225
[2025-02-05T01:12:25.233+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-05T01:12:25.248+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T01:12:25.249+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
